module.exports = {
  content: ["_site/**/*.html", "_site/**/*.js"],
  css: ["_site/assets/css/*.css"],
  output: "_site/assets/css/",
  skippedContentGlobs: ["_site/assets/**/*.html"],
  safelist: {
    greedy: [
      /projects/,
      /project-media/,
      /project-text/,
      /project-links/,
      /no-gutters/,
      /about-banner/,
      /about-contact/,
      /contact-item/,
      /quote-card/,
      /video-container/,
      /media-row/,
      /ratio-16x9/,
      /venue-badge/,
      /section-heading/,
      /entry/,
      /news/,
      /view-transition/,
      /mobile-nav/,
      /mobile-bottom-nav/,
      /about-hero/,
      /hero-credit/,
      /site-/,
      /rail/,
      /topbar/,
      /home-/,
      /work-/,
      /proj-/,
      /xp-/,
      /page-/,
      /prose/,
      /section/,
      /eyebrow/,
      /mono/,
      /publications/,
      /bibliography/,
      /hidden/,
      /open/,
      /light-toggle/,
      /lang-/,
      /pagenav/,
      /rail-animating/,
      /i18n/,
      /topbar/,
      /fa-half-sun-moon/,
    ],
  },
};
