#!/bin/sh
# Git pre-push hook: run the site's QA loop; refuse the push if it fails.
# Install: ln -sf ../../tools/qa/pre-push .git/hooks/pre-push
cd "$(git rev-parse --show-toplevel)/tools/qa" && npm run --silent qa
